# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Spelling
                                 A QGIS plugin
 Check the spelling of words in Print Layout elements
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-15
        copyright            : (C) 2024 by Ian Turton, GDSG, University of Glasgow
        email                : ian@ianturton.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Spelling class from file Spelling.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .spelling import Spelling
    return Spelling(iface)
